#!/bin/zsh --login

set -e

export DESKTOP_ROOT=$(dirname $(dirname $(readlink $0)))

eval $(dbus-launch --sh-syntax --exit-with-session)

eval $(gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL
export SSH_AUTH_SOCK
export GPG_AGENT_INFO

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -dx

zeitgeist-daemon -r &

xcompmgr &

tianbar &

nm-applet &

gnome-screensaver &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

(sleep 120 && /usr/lib/deja-dup/deja-dup/deja-dup-monitor) &

setxkbmap -option altwin:swap_alt_win

if [ -f ~/.fehbg ]
then
	eval $(cat ~/.fehbg)
fi

$DESKTOP_ROOT/edit-server/edit-server &

exec xmonad
