#!/bin/zsh --login

# LightDM runs this in bash
echo "shell is $shell" >&2
if [ "$shell" != "zsh" ]
then
	exec zsh $0
fi

set -e

# global /etc/zshprofile overrides $PATH
. $HOME/.zshenv

export DESKTOP_ROOT=$(dirname $(dirname $(readlink $0)))

eval $(dbus-launch --sh-syntax --exit-with-session)

eval $(gnome-keyring-daemon --replace --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL
export SSH_AUTH_SOCK
export GPG_AGENT_INFO

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -dx

xcompmgr &

fix-env &

light-locker &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

chrome_edit_server &

tianbar &

exec xmonad
