# FIXME: Docker Desktop keeps re-adding its PATH here, but seems to leave the
# file alone with just its comments:
# The following lines were added by Docker Desktop to add commands to your PATH.
# End of Docker Desktop section.

typeset -U path

if [ -d /opt/homebrew ]
then
    path=(/opt/homebrew/bin $path)
fi

if [ -d ~/.local/share/mise/shims ]
then
    path=(~/.local/share/mise/shims $path)
fi

if [ -d ~/.cargo/bin ]
then
    path=(~/.cargo/bin $path)
fi

path=(~/.local/bin $path)

export PATH
