typeset -U path
path=(~/bin ~/.local/bin $path)

export PAGER=less
export LESS='-RFX'
export EDITOR=emacsclient

export WORKON_HOME=~/.virtualenvs

if [ "$COLORTERM" = "gnome-terminal" ] && [ "$TERM" = "xterm" ]
then
    export TERM=xterm-256color
fi
