typeset -U path
if [ -d /opt/homebrew ]
then
    path=(/opt/homebrew/bin $path)
fi
path=(~/.local/bin $path)
export PATH

export PAGER=less
export LESS='-RFX'
export EDITOR=nvim
alias vim=nvim

e() {
    ${(z)EDITOR} "$@"
}

export _JAVA_AWT_WM_NONREPARENTING=1
