typeset -U path
path=(~/bin ~/.local/bin $path)

export PAGER=less
export LESS='-RFX'
export EDITOR="emacsclient --alternate-editor emacs"
export TERM=xterm-256color

e() {
    ${(z)EDITOR} "$@"
}

export WORKON_HOME=~/.virtualenvs
