HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory nomatch hist_ignore_all_dups hist_ignore_space
unsetopt autocd

autoload -Uz compinit
compinit

export DESKTOP_ROOT=$(dirname $(dirname $(readlink ~/.zshrc)))

alias grep='grep --color=auto'

bindkey -e

# X terminal keys
bindkey '^[[1;5D' vi-backward-word
bindkey '^[[1;5C' vi-forward-word
bindkey '^[OF' vi-end-of-line
bindkey '^[OH' vi-beginning-of-line
bindkey '^[[3~' delete-char
bindkey '^[[3;5~' delete-word

# Non-X terminal keys, where different
bindkey '^[[D' vi-backward-word
bindkey '^[[C' vi-forward-word
bindkey '^[[4~' vi-end-of-line
bindkey '^[[1~' vi-beginning-of-line

# macOS terminal keys, where different
bindkey '^[^[[D' vi-backward-word
bindkey '^[^[[C' vi-forward-word

# Edit the command line with Ctrl-V
bindkey '^V' edit-command-line

source ~/.zgen/zgen.zsh

DISABLE_VENV_CD=1
DISABLE_UPDATE_PROMPT=true
if ! zgen saved; then
    echo 'Creating a zgen save'

    zgen oh-my-zsh

    zgen oh-my-zsh plugins/autojump
    zgen oh-my-zsh plugins/bower
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/npm
    zgen oh-my-zsh plugins/stack

    zgen load zsh-users/zsh-autosuggestions

    zgen load zsh-users/zsh-syntax-highlighting

    zgen load petervanderdoes/git-flow-completion

    zgen save
fi

# Theme
if [ $HOST = taohua ]
then
    PROMPT_HOST=桃花
elif [ $HOST = liushu ]
then
    PROMPT_HOST=柳树
else
    PROMPT_HOST=$HOST
fi

PROMPT='%{$fg[green]%}$PROMPT_HOST%{$reset_color%} %~ \
$(git_prompt_info)\
%{$fg[red]%}%(!.#.»)%{$reset_color%} '
PROMPT2='%{$fg[red]%}\ %{$reset_color%}'
RPS1='%(?..%{$fg[red]%}%? ↵%{$reset_color%})'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[green]%}±%{$fg[yellow]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_CLEAN=""
ZSH_THEME_GIT_PROMPT_DIRTY="⚡"

ZSH_THEME_TERM_TITLE_IDLE="$PROMPT_HOST: %~"

# global /etc/zshprofile overrides $PATH
# oh-my-zsh overrides $PAGER
source $HOME/.zshenv

if [ -f /etc/profile.d/vte.sh ]
then
    source /etc/profile.d/vte.sh
fi
