#!/bin/bash

set -e

DIR=$(readlink -f $(dirname $0))

# Packages
# TODO: obnam
sudo dnf copr enable -y pschyska/alacritty
# sudo dnf copr enable -y mikelo2/keeweb
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
sudo dnf install -y \
  alacritty \
  curl \
  docker \
  ghc \
  git \
  git-lfs \
  hlint \
  htop \
  jq \
  lsof \
  KeeWeb \
  meld \
  moreutils \
  mosh \
  mozilla-fira-mono-fonts \
  nmap \
  nodejs \
  npm \
  pwgen \
  python \
  python3 \
  ripgrep \
  rlwrap \
  rsync \
  snapd \
  strace \
  tcpdump \
  tig \
  tmux \
  util-linux-user \
  vim \
  vlc \
  wget \
  yarn \
  youtube-dl \
  zsh \
  && true
sudo ln -sf /var/lib/snapd/snap /snap

# Systemd
sudo systemctl enable --no-reload \
  docker \
  sshd \
  && true
# Ignore reload errors if running in chroot
sudo systemctl daemon-reload || true

# Inotify limits
echo 'fs.inotify.max_user_watches = 524288' | sudo tee /etc/sysctl.d/50-inotify.conf
sudo sysctl -p --system

# Shell
if [ $(getent passwd $USER | cut -d: -f7) != "/bin/zsh" ]
then
  chsh -s /bin/zsh
fi

# User packages
mkdir -p $HOME/.local/bin

STACK_OS=linux
curl -sSL https://get.haskellstack.org/stable/${STACK_OS}-x86_64.tar.gz | tar -z -x --strip 1 -C $HOME/.local/bin '*/stack'

DHALL_VERSION=1.32.0
DHALL_JSON_VERSION=1.6.4
DHALL_YAML_VERSION=1.1.0
DHALL_OS=linux

curl -sSL https://github.com/dhall-lang/dhall-haskell/releases/download/${DHALL_VERSION}/dhall-json-${DHALL_JSON_VERSION}-x86_64-${DHALL_OS}.tar.bz2 | tar -j -x -C $HOME/.local './bin/*dhall*'
curl -sSL https://github.com/dhall-lang/dhall-haskell/releases/download/${DHALL_VERSION}/dhall-yaml-${DHALL_YAML_VERSION}-x86_64-${DHALL_OS}.tar.bz2 | tar -j -x -C $HOME/.local './bin/*dhall*'

# User configuration
$DIR/makelinks
