#!/bin/sh -e

DIR=`pwd`/`dirname $0`

# XMonad
sudo apt-get -y install xmonad

mkdir -p ~/.xmonad
ln -sf $DIR/xmonad.hs ~/.xmonad

# Taffybar
sudo apt-get -y install cabal-install
cabal update
sudo apt-get -y install gtk2hs-buildtools libghc-cairo-dev libghc-gtk-dev \
	libgtk-3-dev
cabal install taffybar

sudo apt-get -y install light-themes

ln -sf $DIR/taffybar ~/.config

# Synapse
sudo apt-get -y install synapse zeitgeist-extension-fts

# IBus
sudo apt-get -y install ibus ibus-pinyin ibus-table

# Session script
ln -sf $DIR/.xsession ~
