#!/bin/bash

set -euo pipefail

ISORT_ARGS=
BLACK_ARGS=
if [ "${1-}" == "--format" ]
then
    ISORT_ARGS=--check
    BLACK_ARGS=--check
fi

source "$(dirname "$0")/functions.sh"

venv

# shellcheck disable=SC2046
shellcheck "$DIR"/*.sh $(grep -l '^#!/bin/bash' "$DIR"/* 2>/dev/null)
isort $ISORT_ARGS "$DIR"/*.py
black $BLACK_ARGS "$DIR"/*.py
mypy "$DIR"/*.py
