#!/usr/bin/env bash

set -euo pipefail

if (git remote -v | grep -q SEEK-Jobs) && (echo "$GIT_AUTHOR_EMAIL" | grep -qv seek.com.au)
then
  git config user.email $USER@seek.com.au
  echo "Please use SEEK email for SEEK repositories (set for you now, retry the commit)." >&2
  exit 1
fi
