if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-commentary'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-sleuth'
Plug 'sgur/vim-editorconfig'
Plug 'sonph/onehalf', {'rtp': 'vim/'}

call plug#end()

au FileType html setlocal tabstop=2 expandtab colorcolumn=

au FileType javascript setlocal tabstop=2 expandtab

au FileType css setlocal tabstop=2 expandtab
au FileType less setlocal tabstop=2 expandtab

au FileType yaml setlocal tabstop=2 expandtab

au FileType json setlocal tabstop=2 expandtab

set wildignore+=node_modules

au FileType haskell setlocal tabstop=4 expandtab
au FileType haskell setlocal formatprg=hindent

au FileType cabal setlocal tabstop=2 expandtab

au FileType hamlet setlocal tabstop=2 expandtab

au FileType python setlocal tabstop=4 expandtab
au FileType htmldjango setlocal tabstop=2 expandtab colorcolumn=

set wildignore+=dist,htmlcov,*.pyc

" Generic
colorscheme onehalflight

syntax on
filetype plugin indent on
set hlsearch

if exists('+colorcolumn')
	set colorcolumn=80
endif

set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

" Follow tabstop
set softtabstop=-1 shiftwidth=0

set history=1000
if exists('+undofile')
	set undofile
endif
if exists('+undodir')
	set undodir=$HOME/.vim/undo
endif
if exists('+undolevels')
	set undolevels=1000
endif
if exists('+undoreload')
	set undoreload=10000
endif

set ignorecase smartcase

set number relativenumber

set completeopt-=preview

" Autosave
set updatetime=250
autocmd CursorHold * update

imap <C-BS> <C-W>
imap <C-Del> <C-O>de

let g:EditorConfig_exclude_patterns = ['fugitive://.*']

command! W w !sudo sponge %

set exrc
