PageSize=5
CloudPinyinEnabled=True
PredictionSize=10
FirstRun=False

[PrevPage]
0=minus
1=Up
2=KP_Up

[NextPage]
0=equal
1=Down
2=KP_Down

[ChooseCharFromPhrase]
0=bracketleft
1=bracketright

[QuickPhraseTriggerRegex]
0=.(/|@)$
1="^(www|bbs|forum|mail|bbs)\\\\."
2=^(http|https|ftp|telnet|mailto):

