flags: {}
packages: []
extra-deps:
- gi-cairo-1.0.6
- gi-gdk-3.0.6
- gi-gio-2.0.6
- gi-gtk-3.0.6
- gi-javascriptcore-4.0.6
- gi-webkit2-4.0.6
- optparse-declarative-0.3.0
- X11-xft-0.3.1
- xmonad-contrib-0.12
resolver: lts-7.8
