- repo: sharkdp/bat
  binary: bat
  strip: 1
- name: cargo
  applicable: linux
- name: colordiff
- name: coreutils
  applicable: darwin
- name: curl
- repo: dhall-lang/dhall-haskell
  prefix: dhall-json
  binary: dhall-to-json
- repo: dhall-lang/dhall-haskell
  prefix: dhall-yaml
  binary: dhall-to-yaml
- repo: Wilfred/difftastic
  binary: difft
- name: g++
  applicable: linux
- name: gcc
- name: ghc
- name: git
- name: git-lfs
- repo: dandavison/delta
  binary: delta
  strip: 1
- name: gnu-sed
  applicable: darwin
- name: gnu-tar
  applicable: darwin
- name: ipython
  applicable: darwin
- name: jq
- name: htop
- name: lsof
- name: make
- name: moreutils
- name: neovim
  applicable: darwin
- name: nmap
- name: node
  applicable: darwin
- name: nodejs
  applicable: linux
- name: npm
  applicable: linux
- name: pwgen
- name: python3-ipython
  applicable: linux
- name: rar
  applicable: darwin
- name: ripgrep
- name: rlwrap
- name: rsync
- repo: koalaman/shellcheck
  binary: shellcheck
  strip: 1
- repo: commercialhaskell/stack
  suffix: tar.gz
  exclude: static
  strip: 1
  binary: stack
- name: strace
  applicable: linux
- name: tig
- name: unrar-free
  applicable: linux
- name: wget
- url: https://yarnpkg.com/latest.tar.gz
  binary: yarn
  binary_wrapper: true
  strip: 1
- name: zsh
