- links: dotfiles
  destination: ""
  dot: true
- links: bin
  destination: .local/bin
  shallow: true
- links: config
  destination: .config
  shallow: true
  post: ~/.config/karabiner/apply
- links: dotfiles
  destination: ""
  dot: true
  root: true
  only:
    - dircolors
    - zshrc
    - zshenv
- links: config
  destination: .config
  root: true
  shallow: true
  only:
    - bat
    - nvim
    - git
- repo: ast-grep/ast-grep
  binary: ast-grep
- repo: atuinsh/atuin
  binary: atuin
  exclude: update
- repo: sharkdp/bat
  binary: bat
- system: colordiff
- system: curl
- repo: dhall-lang/dhall-haskell
  prefix: dhall-json
  binary: dhall-to-json
- repo: dhall-lang/dhall-haskell
  prefix: dhall-lsp-server
  binary: dhall-lsp-server
- repo: Wilfred/difftastic
  binary: difft
- repo: Byron/dua-cli
  binary: dua
- repo: eza-community/eza
  binary: eza
  exclude:
    - static
    - zip
  $if:
    os: linux
- system: eza
  $if:
    os: darwin
- repo: fastfetch-cli/fastfetch
  binary: fastfetch
  exclude:
    - polyfilled
    - zip
- repo: sharkdp/hexyl
  binary: hexyl
- system: g++
  $if:
    os: linux
- system: gcc
- repo: cli/cli
  binary: gh
- system: git
- system: git-lfs
- repo: tummychow/git-absorb
  binary: git-absorb
- repo: dandavison/delta
  binary: delta
- system: jq
- system: htop
- system: lftp
- system: lsof
- system: make
- repo: jdx/mise
  suffix: .tar.xz
  binary: mise
- system: moreutils
- system: ncdu
- repo: neovim/neovim
  binary: nvim
- clone: nyoom-engineering/oxocarbon.nvim
  destination: .local/share/nvim/site/pack/mybox/start/oxocarbon
- clone: numToStr/Comment.nvim
  destination: .local/share/nvim/site/pack/mybox/start/Comment.nvim
- clone: tpope/vim-sleuth
  destination: .local/share/nvim/site/pack/mybox/start/vim-sleuth
- clone: sgur/vim-editorconfig
  destination: .local/share/nvim/site/pack/mybox/start/vim-editorconfig
- clone: junegunn/vim-easy-align
  destination: .local/share/nvim/site/pack/mybox/start/vim-easy-align
- clone: nvim-lua/plenary.nvim
  destination: .local/share/nvim/site/pack/mybox/start/plenary.nvim
- clone: nvim-telescope/telescope.nvim
  destination: .local/share/nvim/site/pack/mybox/start/telescope.nvim
- clone: smartpde/telescope-recent-files
  destination: .local/share/nvim/site/pack/mybox/start/telescope-recent-files
- clone: nvim-treesitter/nvim-treesitter
  destination: .local/share/nvim/site/pack/mybox/start/nvim-treesitter
  post: nvim +'set nomore' +TSUpdateSync +q
- clone: https://gitlab.com/HiPhish/rainbow-delimiters.nvim.git
  destination: .local/share/nvim/site/pack/mybox/start/rainbow-delimiters.nvim
- system: nmap
- system: pkgconf
  $if:
    os: darwin
- system: psmisc
  $if:
    os: linux
- system: pstree
  $if:
    os: darwin
- system: pv
- system: pwgen
- repo: claudiodangelis/qrcp
  binary: qrcp
- system: rar
  $if:
    os: darwin
- system: unrar-free
  $if:
    os: linux
- repo: BurntSushi/ripgrep
  binary: rg
- system: rlwrap
- system: rsync
- repo: koalaman/shellcheck
  binary: shellcheck
- system: strace
  $if:
    os: linux
- system: tig
- repo: sachaos/viddy
  binary: viddy
- system: wget
  $if:
    os: darwin
- system: wget2
  $if:
    os: debian
- system: wget2-wget
  $if:
    os: fedora
- repo: mikefarah/yq
  exclude: .tar.gz
  binary: yq
  raw: yq
- system: zsh
- shell: /bin/zsh
- clone: zsh-users/zsh-autosuggestions
  destination: .zsh-plugins/zsh-autosuggestions
- clone: popstas/zsh-command-time
  destination: .zsh-plugins/zsh-command-time
- clone: zsh-users/zsh-syntax-highlighting
  destination: .zsh-plugins/zsh-syntax-highlighting
- clone: agkozak/zsh-z
  destination: .zsh-plugins/zsh-z
- clone: ohmyzsh/ohmyzsh
  destination: .zsh-plugins/oh-my-zsh
