- links: dotfiles
  destination: ''
  dot: true
- links: bin
  destination: .local/bin
  shallow: true
- links: config
  destination: .config
  shallow: true
- links: dotfiles
  destination: ''
  dot: true
  root: true
  only:
    - dircolors
    - zshrc
    - zshenv
- links: config
  destination: .config
  root: true
  shallow: true
  only:
    - bat
    - nvim
    - git
- repo: ellie/atuin
  binary: atuin
  strip: 1
- repo: sharkdp/bat
  binary: bat
  strip: 1
- system: colordiff
- system: curl
- repo: Wilfred/difftastic
  binary: difft
- repo: eza-community/eza
  binary: eza
  exclude: static
- repo: sharkdp/hexyl
  binary: hexyl
  strip: 1
- system: g++
- system: gcc
- repo: cli/cli
  strip: 1
  binary: gh
- system: git
- system: git-lfs
- repo: tummychow/git-absorb
  binary: git-absorb
  strip: 1
  exclude: arm
- repo: dandavison/delta
  binary: delta
  strip: 1
- repo: ndmitchell/hlint
  strip: 1
  binary: hlint
- system: jq
- system: htop
- system: lftp
- system: lsof
- system: make
- system: moreutils
- repo: neovim/neovim
  strip: 1
  binary: nvim
  app: nvim
  root: true
- clone: savq/paq-nvim
  destination: .local/share/nvim/site/pack/paqs/start/paq-nvim
- system: nmap
- system: nodejs
- system: nodejs-npm
  distribution: fedora
- system: npm
  distribution: debian
- clone: nvm-sh/nvm
  destination: .nvm
- pipx: poetry
- system: pv
- system: pwgen
- system: python3-ipython
- system: ripgrep
- system: rlwrap
- system: rsync
- repo: koalaman/shellcheck
  binary: shellcheck
  strip: 1
- system: strace
- system: tig
- system: unrar-free
- repo: sachaos/viddy
  binary: viddy
- system: wget
- url: https://yarnpkg.com/latest.tar.gz
  binary: yarn
  binary_wrapper: true
  strip: 1
- system: zsh
- shell: /bin/zsh
- clone: z-shell/zi
  destination: .zi/bin
- npm: git-json-merge
  binary: git-json-merge
