- repo: sharkdp/bat
  binary: bat
  strip: 1
- name: cargo
- name: colordiff
- name: coreutils
  applicable: darwin
- name: curl
- repo: dhall-lang/dhall-haskell
  prefix: dhall-json
  binary: dhall-to-json
- repo: dhall-lang/dhall-haskell
  prefix: dhall-yaml
  binary: dhall-to-yaml
- name: g++
- name: gcc
- name: ghc
- name: git
- name: git-lfs
- repo: dandavison/delta
  binary: delta
  strip: 1
- name: gnu-sed
  applicable: darwin
- name: gnu-tar
  applicable: darwin
- name: ipython
- name: jq
- name: htop
- name: lsof
- name: make
- name: moreutils
- name: neovim
  applicable: darwin
- name: nmap
- name: node
- name: rar
  applicable: darwin
- name: ripgrep
- name: rlwrap
- name: rust
- name: rsync
- name: strace
- name: tig
- name: unrar
  applicable: linux
- name: wget
- name: zsh
