- links: dotfiles
  destination: ''
  dot: true
- links: bin
  destination: .local/bin
  shallow: true
- links: config
  destination: .config
  shallow: true
- links: dotfiles
  destination: ''
  dot: true
  root: true
  only:
    - dircolors
    - zshrc
    - zshenv
- links: config
  destination: .config
  root: true
  shallow: true
  only:
    - bat
    - nvim
    - git
- repo: sharkdp/bat
  binary: bat
  strip: 1
- name: colordiff
- name: coreutils
  os: darwin
- name: curl
- repo: dhall-lang/dhall-haskell
  prefix: dhall-json
  binary: dhall-to-json
- repo: dhall-lang/dhall-haskell
  prefix: dhall-yaml
  binary: dhall-to-yaml
- repo: Wilfred/difftastic
  binary: difft
- repo: ogham/exa
  binary: exa
- name: g++
  os: linux
- name: gcc
- repo: cli/cli
  strip: 1
  binary: gh
- name: ghc
- name: git
- name: git-lfs
- repo: dandavison/delta
  binary: delta
  strip: 1
- name: gnu-sed
  os: darwin
- name: gnu-tar
  os: darwin
- repo: ndmitchell/hlint
  strip: 1
  binary: hlint
- name: ipython
  os: darwin
- name: jq
- clone: jenv/jenv
  destination: .jenv
- name: htop
- name: lsof
- name: make
- name: moreutils
- repo: neovim/neovim
  strip: 1
  binary: nvim
  app: nvim
  root: true
- clone: savq/paq-nvim
  destination: .local/share/nvim/site/pack/paqs/start/paq-nvim
- name: nmap
- name: node
  os: darwin
- name: nodejs
  os: linux
- name: npm
  os: linux
- clone: nvm-sh/nvm
  destination: .nvm
- pip: pipx
- pipx: poetry
- name: pv
- name: pwgen
- name: python3-ipython
  os: linux
- name: homebrew/cask/rar
  os: darwin
- name: ripgrep
- name: rlwrap
- name: rsync
- repo: koalaman/shellcheck
  binary: shellcheck
  strip: 1
- repo: commercialhaskell/stack
  exclude: static
  strip: 1
  binary: stack
- name: strace
  os: linux
- name: tig
- name: unrar-free
  os: linux
- repo: sachaos/viddy
  binary: viddy
- name: wget
- url: https://yarnpkg.com/latest.tar.gz
  binary: yarn
  binary_wrapper: true
  strip: 1
- name: zsh
- shell: /bin/zsh
  os: linux
- shell: /usr/local/bin/zsh
  os: darwin
