- repo: sharkdp/bat
  binary: bat
  strip: 1
- name: colordiff
- name: coreutils
  os: darwin
- name: curl
- repo: dhall-lang/dhall-haskell
  prefix: dhall-json
  binary: dhall-to-json
- repo: dhall-lang/dhall-haskell
  prefix: dhall-yaml
  binary: dhall-to-yaml
- repo: Wilfred/difftastic
  binary: difft
- name: g++
  os: linux
- name: gcc
- repo: cli/cli
  strip: 1
  binary: gh
- name: ghc
- name: git
- name: git-lfs
- repo: dandavison/delta
  binary: delta
  strip: 1
- name: gnu-sed
  os: darwin
- name: gnu-tar
  os: darwin
- repo: ndmitchell/hlint
  strip: 1
  binary: hlint
- name: ipython
  os: darwin
- name: jq
- clone: jenv/jenv
  destination: .jenv
- name: htop
- name: lsof
- name: make
- name: moreutils
- repo: neovim/neovim
  exclude: sha256sum
  strip: 1
  binary: nvim
  app: nvim
  as_global: true
- name: nmap
- name: node
  os: darwin
- name: nodejs
  os: linux
- name: npm
  os: linux
- clone: nvm-sh/nvm
  destination: .nvm
- name: pipx
- pipx: poetry
- name: pv
- name: pwgen
- name: python3-ipython
  os: linux
- name: rar
  os: darwin
- name: ripgrep
- name: rlwrap
- name: rsync
- repo: koalaman/shellcheck
  binary: shellcheck
  strip: 1
- repo: commercialhaskell/stack
  suffix: tar.gz
  exclude: static
  strip: 1
  binary: stack
- name: strace
  os: linux
- name: tig
- name: unrar-free
  os: linux
- name: wget
- url: https://yarnpkg.com/latest.tar.gz
  binary: yarn
  binary_wrapper: true
  strip: 1
- name: zsh
