- links: dotfiles
  destination: ''
  dot: true
- links: bin
  destination: .local/bin
  shallow: true
- links: config
  destination: .config
  shallow: true
- links: dotfiles
  destination: ''
  dot: true
  root: true
  only:
    - dircolors
    - zshrc
    - zshenv
- links: config
  destination: .config
  root: true
  shallow: true
  only:
    - bat
    - nvim
    - git
- clone: asdf-vm/asdf
  destination: .asdf
- clone: andrewthauer/asdf-alias
  destination: .asdf/plugins/alias
- clone: halcyon/asdf-java
  destination: .asdf/plugins/java
- clone: asdf-vm/asdf-nodejs
  destination: .asdf/plugins/nodejs
- repo: ast-grep/ast-grep
  binary: sg
- repo: ellie/atuin
  binary: atuin
- repo: sharkdp/bat
  binary: bat
- system: colordiff
- system: curl
- repo: Wilfred/difftastic
  binary: difft
- repo: eza-community/eza
  binary: eza
  exclude:
    - static
    - zip
- repo: sharkdp/hexyl
  binary: hexyl
- system: g++
  os: linux
- system: gcc
- repo: cli/cli
  binary: gh
- system: git
- system: git-lfs
- repo: tummychow/git-absorb
  binary: git-absorb
- repo: dandavison/delta
  binary: delta
- repo: ndmitchell/hlint
  binary: hlint
- system: jq
- system: htop
- system: lftp
- system: lsof
- system: make
- system: moreutils
- repo: neovim/neovim
  binary: nvim
  app: nvim
  root: true
- clone: savq/paq-nvim
  destination: .local/share/nvim/site/pack/paqs/start/paq-nvim
- system: nmap
- system: nodejs
  os: linux
- system: nodejs-npm
  os: linux
  distribution: fedora
- system: npm
  os: linux
  distribution: debian
- system: node
  os: darwin
- pipx: poetry
- system: pv
- system: pwgen
- system: python3-ipython
  os: linux
- system: ipython
  os: darwin
- system: homebrew/cask/rar
  os: darwin
- system: unrar-free
  os: linux
- repo: BurntSushi/ripgrep
  binary: rg
- system: rlwrap
- system: rsync
- repo: koalaman/shellcheck
  binary: shellcheck
- system: strace
  os: linux
- system: tig
- repo: sachaos/viddy
  binary: viddy
- system: wget
- url: https://yarnpkg.com/latest.tar.gz
  binary: yarn
  binary_wrapper: true
- system: zsh
- shell: /bin/zsh
- clone: z-shell/zi
  destination: .zi/bin
- clone: zsh-users/zsh-autosuggestions
  destination: .zsh-plugins/zsh-autosuggestions
- clone: popstas/zsh-command-time
  destination: .zsh-plugins/zsh-command-time
- clone: zsh-users/zsh-syntax-highlighting
  destination: .zsh-plugins/zsh-syntax-highlighting
- clone: agkozak/zsh-z
  destination: .zsh-plugins/zsh-z
