- links: dotfiles
  destination: ''
  dot: true
- links: bin
  destination: .local/bin
  shallow: true
- links: config
  destination: .config
  shallow: true
- links: dotfiles
  destination: ''
  dot: true
  root: true
  only:
    - dircolors
    - zshrc
    - zshenv
- links: config
  destination: .config
  root: true
  shallow: true
  only:
    - bat
    - nvim
    - git
- repo: ellie/atuin
  binary: atuin
  strip: 1
- repo: sharkdp/bat
  binary: bat
  strip: 1
- name: colordiff
- name: curl
- repo: Wilfred/difftastic
  binary: difft
- repo: eza-community/eza
  raw: eza
  raw_executable: true
  binary: eza
- repo: sharkdp/hexyl
  binary: hexyl
  strip: 1
- name: g++
- name: gcc
- repo: cli/cli
  strip: 1
  binary: gh
- name: git
- name: git-lfs
- repo: tummychow/git-absorb
  binary: git-absorb
  strip: 1
  exclude: arm
- repo: dandavison/delta
  binary: delta
  strip: 1
- repo: ndmitchell/hlint
  strip: 1
  binary: hlint
- name: jq
- name: htop
- name: lftp
- name: lsof
- name: make
- name: moreutils
- repo: neovim/neovim
  strip: 1
  binary: nvim
  app: nvim
  root: true
- clone: savq/paq-nvim
  destination: .local/share/nvim/site/pack/paqs/start/paq-nvim
- name: nmap
- name: nodejs
- name: nodejs-npm
  distribution: fedora
- name: npm
  distribution: debian
- clone: nvm-sh/nvm
  destination: .nvm
- pipx: poetry
- name: pv
- name: pwgen
- name: python3-ipython
- name: ripgrep
- name: rlwrap
- name: rsync
- repo: koalaman/shellcheck
  binary: shellcheck
  strip: 1
- name: strace
- name: tig
- name: unrar-free
- repo: sachaos/viddy
  binary: viddy
- name: wget
- url: https://yarnpkg.com/latest.tar.gz
  binary: yarn
  binary_wrapper: true
  strip: 1
- name: zsh
- shell: /bin/zsh
- clone: z-shell/zi
  destination: .zi/bin
- npm: git-json-merge
  binary: git-json-merge
