- yum_name: vscode
  yum_url: https://packages.microsoft.com/yumrepos/vscode
  gpg_key: https://packages.microsoft.com/keys/microsoft.asc
  $if:
    os: fedora
- yum_name: docker
  yum_url: 'https://download.docker.com/linux/fedora/$releasever/$basearch/stable'
  gpg_key: https://download.docker.com/linux/fedora/gpg
  $if:
    os: fedora
- system: code
  $if:
    os: linux
- system: visual-studio-code
  auto_updates: true
  $if:
    os: darwin
- system: insomnia
  $if:
    os: darwin
- repo: Kong/insomnia
  prefix: Insomnia.Core
  suffix: tar.gz
  binary: insomnia
  $if:
    os: linux
- system: meld
  $if:
    os: linux
- system: kdiff3
  $if:
    os: darwin
- url: https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
  raw: true
  binary: rustup-init
  $if:
    os: linux
- url: https://static.rust-lang.org/rustup/dist/aarch64-apple-darwin/rustup-init
  raw: true
  binary: rustup-init
  $if:
    os: darwin
- system: tcpdump
