- yum_name: vscode
  yum_url: https://packages.microsoft.com/yumrepos/vscode
  gpg_key: https://packages.microsoft.com/keys/microsoft.asc
  $if:
    os: fedora
- yum_name: docker
  yum_url: 'https://download.docker.com/linux/fedora/$releasever/$basearch/stable'
  gpg_key: https://download.docker.com/linux/fedora/gpg
  $if:
    os: fedora
- system:
    $switch: os
    linux: code
    darwin: visual-studio-code
  auto_updates:
    $switch: os
    darwin: true
- $switch: os
  linux:
    repo: Kong/insomnia
    prefix: Insomnia.Core
    suffix: tar.gz
    binary: insomnia
  darwin:
    system: insomnia
- system: meld
  $if:
    os: linux
- system: kdiff3
  $if:
    os: darwin
- system: tcpdump
